workflows:
  build:
    name: Build and Deploy
    steps:
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Flask app
          command: |
            python app.py
